services:
    frontend:
        build: ./frontend
        ports:
            - "3001:3001"
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_API_URL=${BACKEND_URL:-http://localhost:5001}
            - NODE_ENV=development
        depends_on:
            - backend
        networks:
            - app-network

    backend:
        build: ./backend
        ports:
            - "5001:5001"
        environment:
            - PORT=5001
            - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3001}
            - NODE_ENV=development
            - MONGODB_URI=mongodb://mongo:27017/saas_db
            - CLIENT_URL=https://localhost:3001
            - JWT_SECRET=your_jwt_secret
            - OPENAI_API_KEY=${OPENAI_API_KEY}
        depends_on:
            - mongo
        networks:
            - app-network

    mongo:
        image: mongo:6.0
        platform: linux/amd64
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        networks:
            - app-network
        healthcheck:
            test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s

volumes:
    mongo-data:

networks:
    app-network:
        driver: bridge