version: '3'

services:
    frontend:
        build: ./frontend
        ports:
            - "3001:3001"
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_API_URL=http://localhost:5001
            - REACT_APP_STRIPE_PUBLISHABLE_KEY=STRIPE_PUBLISHABLE_KEY=pk_live_51BQIZJFRs2YmnLPIMK5D38WojCyNq7yQmzeV0EN7Jw47Wmu5Ev3vXF6XoP1lcIkd4ANVFDPrQNXeochTbw7WqYoG00p482Dh50
        depends_on:
            - backend

    backend:
        build: ./backend
        ports:
            - "5001:5001"
        environment:
            - PORT=5001
            - FRONTEND_URL=http://localhost:3001
            - MONGODB_URI=mongodb://mongo:27017/saas_db
            - JWT_SECRET=jwtsecret
            - STRIPE_SECRET_KEY=sk_live_DtWUZU35ETDC7rpLEf8lZVId
            - STRIPE_WEBHOOK_SECRET=whsec_lk5U1PzTE51YrRHQsI3NtbsMPSsQHcPr
            - CLIENT_URL=https://localhost:3001
        depends_on:
            - mongo

    mongo:
        image: mongo
        ports:
            - "${MONGO_PORT:-27017}:27017"
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data: