services:
    frontend_${projectId}:
        build: ./frontend
        ports:
            - "3001:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_API_URL=http://localhost:5001
        depends_on:
            - backend

    backend_${projectId}:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5001:5000"
        environment:
            - MONGODB_URI=mongodb://mongo_${projectId}:27017/todoapp
        volumes:
            - ./backend:/app
            - /app/node_modules
        depends_on:
            - mongo_${projectId}

        mongo_${projectId}:
            image: mongo:4.4
            ports:
                - "27018:27017"
            volumes:
                - mongo_data_${projectId}:/data/db

    volumes:
        mongo_data_${projectId}:
