version: '3'

services:
    frontend:
        build: ./frontend
        ports:
            - "${FRONTEND_PORT:-3001}:3000"
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_API_URL=http://localhost:${BACKEND_PORT:-5001}
            - REACT_APP_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
        depends_on:
            - backend

    backend:
        build: ./backend
        ports:
            - "${BACKEND_PORT:-5001}:5001"
        environment:
            - FRONTEND_URL=http://localhost:${FRONTEND_PORT:-3001}
            - MONGODB_URI=mongodb://mongo:27017/${DB_NAME:-saas_db}
            - JWT_SECRET=${JWT_SECRET}
            - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
            - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
        depends_on:
            - mongo

    mongo:
        image: mongo
        ports:
            - "${MONGO_PORT:-27017}:27017"
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data: