services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_API_URL=http://localhost:5001
        depends_on:
            - backend

    backend:
        build: ./backend
        ports:
            - "5001:5001"
        volumes:
            - ./backend:/app
            - /app/node_modules
        environment:
            - FRONTEND_URL=http://localhost:3000
        depends_on:
            - mongo

    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data:
