version: '3'

services:
    frontend:
        build: ./frontend
        ports:
            - "3001:3001"
        environment:
            - CHOKIDAR_USEPOLLING=true
            - REACT_APP_API_URL=http://localhost:5001
        depends_on:
            - backend

    backend:
        build: ./backend
        ports:
            - "5001:5001"
        environment:
            - PORT=5001
            - FRONTEND_URL=http://localhost:3001
            - MONGODB_URI=mongodb://mongo:27017/saas_db
            - CLIENT_URL=https://localhost:3001
            - JWT_SECRET=your_jwt_secret
        depends_on:
            - mongo

    mongo:
        image: mongo
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data: